config/routes.rb
Rails.application.routes.draw do
  get 'projects/dashboard'
  post 'projects/create'
  root 'projects#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

    validates :name, :description, presence: true
    enum status: %w[propuesta en_progreso terminada]

    #Antes de grabar que revise si esta status presente, si esta entonces 
    #status.save sino status = propuesta
    before_save :has_status

    def has_status
        if self.status.present?
            self.status.save
        else
            self.status = "propuesta"
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    # http_basic_authenticate_with name: "algo", password: "123456", only: :dashboard
    def dashboard
        if params[:search].present?
            @projects = Project.where("status = ?", params[:search])
        else
            @projects = Project.all
        end
    end

    def new
        @project = Project.new
        @statuses = Project.statuses.keys.to_a
    end

    def create
        @project = Project.create(project_params)
    end

    private

    def project_params
        params.require(:project).permit(:name, :description, :starts_on, :finish_on, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/create.html.erb
Esta creado el proyecto

<h2><%= link_to 'Ver proyectos', projects_dashboard_path %></h2>

app/views/projects/dashboard.html.erb
<div class= "pt-5">

    <form class = "form-inline justify-content-end w-100">
        <select name="search" class="form-control mr-sm-2">
            <option value=""> Busca Algo</option>
            <option value= "0" >Propuesta</option>
            <option value= "1" >En Progreso</option>
            <option value= "2" >Terminada</option>

        </select>
        <button type = "submit " class = "btn btn-outline-succes my-2 my-sm-0"> Buscar</button>
    </form>

    <br>

    <table class="table">
        <thead>
            <tr>
                <th scope = "col">Nombre</th>
                <th scope = "col">Descripción</th>
                <th scope = "col">Empieza</th>
                <th scope = "col">Termina</th>
                <th scope = "col">Status</th>
                <th colspan = "3"></th>
            </tr>
        </thead>
        <tbody>
            <% @projects.each do |p| %>
            <tr>
                <td> <%= p.name %> </td>
                <td> <%= p.description %> </td>
                <td> <%= p.starts_on %>  </td>
                <td> <%= p.finish_on %>   </td>
                <td> <%= p.status %>   </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

<h2><%= link_to 'Crear proyecto', root_path %></h2>

app/views/projects/new.html.erb
<div class = "pt-5 mb-2 bg-primary text-dark border border-danger">
    <%= form_with(model: @project, url: "/projects/create", local: true) do |f|%>

    <div class = "form-group">
        <%= f.text_field :name, placeholder: 'Ingrese un nombre', class: 'form-control' %>
    </div>

    <div class = "form-group ">
        <%= f.text_area :description, placeholder: 'Describa su proyecto', class: 'form-control'   %>
    </div>
        
    <div class = "form-group">
        <%= f.date_select :starts_on, class: 'form-control'  %>
    </div>
    
    <div class = "form-group">
        <%= f.datetime_select :finish_on, class: 'form-control'  %>
    </div>

    <div class = "form-group">
        <%= f.select :status, options_for_select(@statuses), {include_blank: true}, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Crear Proyecto', class: 'btn btn-primary' %>
    
    
    <% end %>
</div>